Add Linux support
Do-sth-sharp/VocalShaper pull request #5
Opened 2024-11-23 12:17 UTC by kyv001

In posix systems, `cp` is used instead of `copy`, so the command used to copy files needs to depend on OS type.
On Linux, `Fontconfig` is needed to be linked with the executables.
Also, the dynamic library `juce-full` doesn't work for whatever reason, so the static version `juce-full-static` is used instead.
GCC does not compile (and creates strange error messages) so only LLVM is supported.
SynthEngineDemo.vst3 needs to be installed manually because it is not copied to the right place automatically for some reason.

The vcpkg-overlay is still needed to be updated for VocalShaper to be able to compile on Linux.

2024-11-23 15:46 UTC, FangCunWuChang approved these changes

2024-11-23 16:09 UTC, FangCunWuChang commented
I will test and resolve SynthEngineDemo.vst3 copy and `juce-full` runtime issues on Linux in the near future.

2024-11-23 16:12 UTC, FangCunWuChang requested changes
I will do these later before merging this PR:  
- Test on Linux
- Fixed SynthEngineDemo.vst3 copy issue
- Fixed `juce-full` runtime issue

2024-11-23 16:13 UTC, kyv001 commented
Another problem is that it keeps getting segmentation faults (in ActionDispatcher.cpp ActionDispatcher::dispatch) when creating an audio bus. That makes it not usable on Linux.

2024-11-23 16:43 UTC, kyv001 commented
In `ActionDispatcher::dispatch`, the object `action` is used (`action->getName()`) AFTER it is released. Here I get the name before releasing it, so that it does not segfault.

2024-11-24 06:29 UTC, FangCunWuChang commented
> In `ActionDispatcher::dispatch`, the object `action` is used (`action->getName()`) AFTER it is released. Here I get the name before releasing it, so that it does not segfault.

I understand. Different compilers calculate function parameters in different orders.  
Suggest creating a separate PR for this bug.

2024-11-30 10:10 UTC, kyv001 commented
Need to update vcpkg-overlay to use the `x64-linux-llvm` triplet.

2025-01-31 14:55 UTC, FangCunWuChang approved these changes

2025-02-01 11:27 UTC, merged